### ISSUE TITLE
panic: MarshalBinary cannot marshal a nil pointer.

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-amino#103]
This is from trying to compute the Merkle tree of Commits, where some of them are nil. 

--- FAIL: TestBeginBlockAbsentValidators (0.00s)
panic: MarshalBinary cannot marshal a nil pointer. [recovered]
        panic: MarshalBinary cannot marshal a nil pointer.

goroutine 26 [running]:
testing.tRunner.func1(0xc42018c960)
        /Users/ethanbuchman/goRoot/1.9.4/src/testing/testing.go:711 +0x2d2
panic(0x15a31a0, 0x1825430)
        /Users/ethanbuchman/goRoot/1.9.4/src/runtime/panic.go:491 +0x283
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.(*Codec).MarshalBinary(0xc42009a5a0, 0x15fc100, 0x0, 0x1013088, 0x70, 0x1632400, 0x1, 0xc420920000)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/wire.go:26 +0x2b3
github.com/tendermint/tendermint/wire.MarshalBinary(0x15fc100, 0x0, 0x0, 0x0, 0xc420913100, 0x14, 0x20)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/wire/wire.go:21 +0x41
github.com/tendermint/tendermint/types.hasher.Hash(0x15fc100, 0x0, 0xc420913100, 0x14, 0x20)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/types/block.go:519 +0x85
github.com/tendermint/tendermint/types.(*hasher).Hash(0xc4208df4b0, 0xc420913100, 0x14, 0x20)
        <autogenerated>:1 +0x45
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/merkle.SimpleHashFromHashers(0xc42091e000, 0x2, 0x2, 0xc4208df4b0, 0x2, 0x2)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/merkle/simple_tree.go:76 +0xaa
github.com/tendermint/tendermint/types.(*Commit).Hash(0xc4208f8480, 0x1603440, 0xc40b4e3501, 0xc420908d50)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/types/block.go:366 +0x185
github.com/tendermint/tendermint/types.(*Block).FillHeader(0xc420096e60)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/types/block.go:75 +0x12e
github.com/tendermint/tendermint/types.MakeBlock(0x2, 0xc4204b2300, 0xa, 0x10, 0xc4208f8480, 0xc4209114a8)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/types/block.go:39 +0x12b
github.com/tendermint/tendermint/state.State.MakeBlock(0x1695ae1, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/state/state.go:112 +0x66
github.com/tendermint/tendermint/state.TestBeginBlockAbsentValidators(0xc42018c960)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/state/execution_test.go:77 +0xa1f
testing.tRunner(0xc42018c960, 0x17da430)
        /Users/ethanbuchman/goRoot/1.9.4/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /Users/ethanbuchman/goRoot/1.9.4/src/testing/testing.go:789 +0x2de
exit status 2
FAIL    github.com/tendermint/tendermint/state  0.022s

**Comment by ebuchman** [comment]
Looks like this is expected behavour because of the way we encode nil fields now (ie. as their absence, like in protobuf).

So either need to check for nil before marshalling or wrap it in a struct
