### ISSUE TITLE
decodeReflectBinarySlice should also have a check for negative slices and handle uint64->int overflows

### ISSUE THREAD

**Issue by odeke-em** [tendermint/go-amino#118]
The code in https://github.com/tendermint/go-wire/blob/3d2fb07b5c65de21d624919c4680b1cd1b2cfe90/binary-decode.go#L506-L523

assumes that the length will always be in the range [0, 1<<31)

However, there is a great story in the lines.
* To store the length we save it as a Uvarint whose range is: [0, (1<<64)-1]
* while the range of lengths int is: [0, 1<<31)
Now if an attacker sneaks in a length of exactly 1<<31(valid uint64), that but for int,
that wraps around to -2147483648 and we pass that value unfettered to reflect.MakeSlice.

The problem arises from our checks casting to int from uint64 then doing the checks but then checking if zero as uint64

Given count = uint64(1<<31)

int(1<<31) = -2147483648
1. `if int(count) > len(bz) {`:  this passes because -1 < len(bz) even 0
https://github.com/tendermint/go-wire/blob/3d2fb07b5c65de21d624919c4680b1cd1b2cfe90/binary-decode.go#L512-L523

2. 
https://github.com/tendermint/go-wire/blob/3d2fb07b5c65de21d624919c4680b1cd1b2cfe90/binary-decode.go#L518-L523
count = uint64(1<<31)
so `if count == 0` also passes and voila we just passed

3. https://github.com/tendermint/go-wire/blob/3d2fb07b5c65de21d624919c4680b1cd1b2cfe90/binary-decode.go#L531
```go
reflect.MakeSlice(..., -2147483648, -2147483648)
```

We should fix this is a single cast at the top like this
```go
// Read number of items. 
 var count64 = uint64(0) 
 count64, _n, err = DecodeUvarint(bz) 
 if slide(&bz, &n, _n) && err != nil { 
 	return 
 } 
count := int(count64)
if count < 0 {
        if count64 > 0 {
             err = fmt.Errorf("Integer overflow detected for length with invalid uint64 out of range length %d = %d as int", count64, count)
       } else {
             err = fmt.Errorf("Negative slice lengths are not allowed, got = %d", count)
        }
        return
}

 if count > len(bz) { // Currently, each item takes at least 1 byte. 
 	err = fmt.Errorf("Impossible number of elements (%v) compared to buffer length (%v)", 
 		count, len(bz)) 
 	return 
 } 
  
 // Special case when length is 0. 
 // NOTE: We prefer nil slices. 
 if count == 0 { 
 	rv.Set(info.ZeroValue) 
 	return 
 } 
```

**Comment by odeke-em** [comment]
I both hypothesized this bug this morning before bed and was also able to reproduce it with a fuzzer

```shell
panic: reflect.MakeSlice: negative len

goroutine 1 [running]:
reflect.MakeSlice(0x1146780, 0x1104200, 0xbd7fbdebfdef5fef, 0xbd7fbdebfdef5fef, 0xa, 0x0, 0x0)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/goroot/src/reflect/value.go:2095 +0x2e8
github.com/tendermint/go-wire.(*Codec).decodeReflectBinarySlice(0xc000062180, 0x349a01b, 0x2, 0x1fffe5, 0xc0000b0a80, 0x1104200, 0xc0000a4820, 0x197, 0x10f35bf, 0x6, ...)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/binary-decode.go:531 +0x47d
github.com/tendermint/go-wire.(*Codec)._decodeReflectBinary(0xc000062180, 0x349a010, 0xd, 0x1ffff0, 0xc0000b0a80, 0x1104200, 0xc0000a4820, 0x197, 0x10f35bf, 0x6, ...)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/binary-decode.go:112 +0x212a
github.com/tendermint/go-wire.(*Codec).decodeReflectBinary(0xc000062180, 0x349a010, 0xd, 0x1ffff0, 0xc0000b0a80, 0x1104200, 0xc0000a4820, 0x197, 0x10f35bf, 0x6, ...)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/binary-decode.go:63 +0x4ca
github.com/tendermint/go-wire.(*Codec).decodeReflectBinaryStruct(0xc000062180, 0x349a010, 0xd, 0x1ffff0, 0xc0000b0240, 0x11262c0, 0xc0000a4700, 0x199, 0x10f3ce5, 0x7, ...)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/binary-decode.go:625 +0x63b
github.com/tendermint/go-wire.(*Codec)._decodeReflectBinary(0xc000062180, 0x349a002, 0x1b, 0x1ffffe, 0xc0000b0240, 0x11262c0, 0xc0000a4700, 0x199, 0x10f3ce5, 0x7, ...)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/binary-decode.go:118 +0x1d77
github.com/tendermint/go-wire.(*Codec).decodeReflectBinary(0xc000062180, 0x349a002, 0x1b, 0x1ffffe, 0xc0000b0240, 0x11262c0, 0xc0000a4700, 0x199, 0x10f3ce5, 0x7, ...)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/binary-decode.go:63 +0x4ca
github.com/tendermint/go-wire.(*Codec).decodeReflectBinaryStruct(0xc000062180, 0x349a002, 0x1b, 0x1ffffe, 0xc0000b0000, 0x111c0c0, 0xc0000a4480, 0x199, 0x0, 0x0, ...)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/binary-decode.go:625 +0x63b
github.com/tendermint/go-wire.(*Codec)._decodeReflectBinary(0xc000062180, 0x349a001, 0x1c, 0x1fffff, 0xc0000b0000, 0x111c0c0, 0xc0000a4480, 0x199, 0x0, 0x0, ...)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/binary-decode.go:118 +0x1d77
github.com/tendermint/go-wire.(*Codec).decodeReflectBinary(0xc000062180, 0x349a001, 0x1c, 0x1fffff, 0xc0000b0000, 0x111c0c0, 0xc0000a4480, 0x199, 0x0, 0x0, ...)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/binary-decode.go:63 +0x4ca
github.com/tendermint/go-wire.(*Codec).UnmarshalBinaryBare(0xc000062180, 0x349a001, 0x1c, 0x1fffff, 0x10ff820, 0xc0000a4480, 0x480, 0xc0000a4480)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/wire.go:204 +0x2bf
github.com/tendermint/go-wire.(*Codec).UnmarshalBinary(0xc000062180, 0x349a000, 0x1d, 0x200000, 0x10ff820, 0xc0000a4480, 0xc00004fef0, 0x1064176)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/wire.go:159 +0x184
github.com/tendermint/go-wire/tests/fuzz/binary.Fuzz(0x349a000, 0x1d, 0x200000, 0x10f11b9)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/tests/fuzz/binary/binary.go:16 +0x101
go-fuzz-dep.Main(0x1136258)
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/goroot/src/go-fuzz-dep/main.go:49 +0xad
main.main()
	/var/folders/v3/7z434qpx5v3bw0wh8h2myfpw0000gn/T/go-fuzz-build448749671/gopath/src/github.com/tendermint/go-wire/tests/fuzz/binary/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

**Comment by jaekwon** [comment]
Awesome, thank you.  Fixed on develop, please check it out!
