### ISSUE TITLE
WriteJSON: handle marshaling nil as a top level value

### ISSUE THREAD

**Issue by odeke-em** [tendermint/go-amino#36]
Go's "encoding/json" can successfully marshal a nil value, whether it is typed or not for example https://play.golang.org/p/dZ_N86Onh8 or inlined 
```go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	b, _ := json.Marshal(nil)
	fmt.Printf("%s\n", b)
}
```
which gives `null`

However, our package trips out. The question is: should we allow marshaling `nil` to `null`? I realize that most of the usages of this package is with non-nil values but I was just trying to provide test coverage for `tendermint/types` as per https://github.com/tendermint/tendermint/issues/693 and encountered this. Repro
```go
package main

import (
	"bytes"

	"github.com/tendermint/go-wire"
	"github.com/tendermint/tendermint/types"
)

func main() {
	buf := new(bytes.Buffer)
	var n int
	var err error
	wire.WriteJSON((*types.CanonicalJSONOnceHeartbeat)(nil), buf, &n, &err)
}
```
which gives
```shell
panic: reflect: call of reflect.Value.Field on zero Value

goroutine 1 [running]:
reflect.Value.Field(0x0, 0x0, 0x0, 0x0, 0xc42010c000, 0xc42005df60, 0xc42005df68)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/reflect/value.go:764 +0x12e
github.com/tendermint/go-wire.writeReflectJSON(0x0, 0x0, 0x0, 0x1694d80, 0x149f960, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/emmanuelodeke/go/src/github.com/tendermint/go-wire/reflect.go:970 +0x117b
github.com/tendermint/go-wire.WriteJSON(0x14367e0, 0x0, 0x168b640, 0xc42010c000, 0xc42005df60, 0xc42005df68)
	/Users/emmanuelodeke/go/src/github.com/tendermint/go-wire/wire.go:141 +0x121
main.main()
	/Users/emmanuelodeke/Desktop/experiments/tendermint-data/nil-trip.go:14 +0x84
exit status 2
```

**Comment by odeke-em** [comment]
PS: I encountered this while testing https://github.com/tendermint/tendermint/blob/49653d3e31e34a5da83e16e9ffdcd95a68acd9be/types/heartbeat.go#L24-L30

**Comment by zramsay** [comment]
close?

**Comment by odeke-em** [comment]
@zramsay I doubt this issue is fixed.
